BEGIN;

ALTER TABLE features_orderbook
  ADD COLUMN IF NOT EXISTS depth_bid_top5 DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS depth_ask_top5 DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS imbalance_top5 DOUBLE PRECISION;

COMMIT;